import { AppProvider } from "@/lib/contexts/AppContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"
import { CookieBanner } from "@/lib/components/CookieBanner";
import { Toaster } from "sonner";
import { ServiceWorkerRegistrar } from "@/lib/components/ServiceWorkerRegistrar";
import ClientShell from "@/lib/components/ClientShell";

const inter = Inter({ subsets: ["latin"], display: "swap" });

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://pawlyapp.ch";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Pawly — Le reseau social des animaux en Suisse 🐾",
    template: "%s | Pawly",
  },
  description:
    "La premiere app qui connecte les proprietaires d'animaux en Suisse. Matching par compatibilite, balades, evenements — 26 cantons, toutes les especes. Gratuit.",
  keywords: [
    "animaux",
    "suisse",
    "chien",
    "chat",
    "matching",
    "balade",
    "pawly",
    "animaux de compagnie",
    "promenade chien",
    "rencontre animaux",
    "balade chien suisse",
    "application animaux suisse",
    "playdate animaux",
    "pet meetup switzerland",
    "Haustier App Schweiz",
    "app animali svizzera",
  ],
  authors: [{ name: "Pawly" }],
  creator: "Pawly",
  publisher: "Pawly",
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 },
  },
  openGraph: {
    title: "Pawly — Le reseau social des animaux en Suisse",
    description:
      "Connecte-toi avec des proprietaires d'animaux pres de chez toi. Matching IA, balades, evenements — 26 cantons, gratuit.",
    url: SITE_URL,
    siteName: "Pawly",
    locale: "fr_CH",
    alternateLocale: ["de_CH", "it_CH", "en_GB"],
    type: "website",
    // OG image auto-generated by app/opengraph-image.tsx (1200x630)
  },
  twitter: {
    card: "summary_large_image",
    title: "Pawly — Le reseau social des animaux en Suisse",
    description:
      "Matching IA, balades, evenements — 26 cantons suisses, toutes les especes. Gratuit!",
    // Twitter image auto-generated by app/twitter-image.tsx (1200x630)
  },
  manifest: "/manifest.json",
  alternates: {
    canonical: SITE_URL,
    languages: {
      "fr": SITE_URL,
      "de": SITE_URL,
      "it": SITE_URL,
      "en": SITE_URL,
      "x-default": SITE_URL,
    },
  },
  category: "lifestyle",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover" as const,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0A0806" },
    { media: "(prefers-color-scheme: light)", color: "#0A0806" },
  ],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <head>
        <script dangerouslySetInnerHTML={{ __html: `(function(){try{var t=localStorage.getItem("pawly_theme")||"auto";var e=t;if(t==="auto"){e=window.matchMedia("(prefers-color-scheme: dark)").matches?"nuit":"clair"}var v={"nuit":{"--c-deep":"#0B0F0C","--c-nav":"#111827","--c-card":"#111827","--c-border":"rgba(251,191,36,0.12)","--c-text":"#FFFFFF","--c-text-muted":"#9CA3AF","--c-accent":"#FBBF24"},"aurore":{"--c-deep":"#F5EDE0","--c-nav":"#EDE3D4","--c-card":"#FBF7F0","--c-border":"#D9C9B0","--c-text":"#3D2810","--c-text-muted":"#7A5C3A","--c-accent":"#F59E0B"},"ocean":{"--c-deep":"#E0EBF5","--c-nav":"#D4E2F0","--c-card":"#F0F5FB","--c-border":"#B0C8E0","--c-text":"#1E3A5F","--c-text-muted":"#4A7CAA","--c-accent":"#0EA5E9"},"clair":{"--c-deep":"#F0ECE4","--c-nav":"#E8E2D8","--c-card":"#FAF8F4","--c-border":"#D5CFC5","--c-text":"#1A1714","--c-text-muted":"#5a5550","--c-accent":"#D97706"}};var c=v[e];if(c){var r=document.documentElement;for(var k in c){r.style.setProperty(k,c[k])}r.setAttribute("data-theme",e)}}catch(x){}}())` }} />

        {/* JSON-LD: WebApplication */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebApplication",
              "name": "Pawly",
              "url": "https://pawlyapp.ch",
              "description": "Reseau social pour animaux de compagnie en Suisse. Matching IA, evenements, communaute.",
              "applicationCategory": "SocialNetworkingApplication",
              "operatingSystem": "Web",
              "offers": {
                "@type": "Offer",
                "price": "0",
                "priceCurrency": "CHF"
              },
              "author": {
                "@type": "Organization",
                "name": "Pawly"
              }
            }),
          }}
        />

        {/* JSON-LD: Organization */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "name": "Pawly",
              "url": SITE_URL,
              "logo": `${SITE_URL}/icon-512.png`,
              "description": "Application suisse de mise en relation entre proprietaires d'animaux de compagnie.",
              "address": {
                "@type": "PostalAddress",
                "addressRegion": "Vaud",
                "addressCountry": "CH"
              },
              "sameAs": [],
              "contactPoint": {
                "@type": "ContactPoint",
                "contactType": "customer service",
                "availableLanguage": ["French", "German", "Italian", "English"]
              }
            }),
          }}
        />

        {/* SW registered in ServiceWorkerRegistrar component */}
        {/* theme-color set via viewport export */}
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/icon-192.png" />
        {process.env.NEXT_PUBLIC_SUPABASE_URL && (
          <>
            <link rel="preconnect" href={process.env.NEXT_PUBLIC_SUPABASE_URL} />
            <link rel="dns-prefetch" href={process.env.NEXT_PUBLIC_SUPABASE_URL} />
          </>
        )}
        {/* Inline SW cache nuke — runs before any cached JS chunk */}
        <script dangerouslySetInnerHTML={{ __html: `
          (function(){
            var v=9;
            try{
              var last=Number(localStorage.getItem('_swv')||'0');
              if(last<v){
                localStorage.setItem('_swv',String(v));
                if('caches'in self)caches.keys().then(function(k){return Promise.all(k.map(function(c){return caches.delete(c)}))}).then(function(){
                  if('serviceWorker'in navigator)return navigator.serviceWorker.getRegistrations().then(function(r){return Promise.all(r.map(function(w){return w.unregister()}))});
                }).then(function(){location.reload()}).catch(function(){location.reload()});
                else if('serviceWorker'in navigator)navigator.serviceWorker.getRegistrations().then(function(r){r.forEach(function(w){w.unregister()});location.reload()}).catch(function(){location.reload()});
              }
            }catch(e){}
          })();
        `}} />
      </head>
      <body className={inter.className + " min-h-screen"} style={{ background: "var(--c-deep, #0A0806)", color: "var(--c-text, #F5ECD8)" }}>
        <AppProvider>
          <ClientShell>
            {children}
          </ClientShell>
        </AppProvider>
        <CookieBanner />
        <Toaster position="top-center" richColors />
        <ServiceWorkerRegistrar />
      </body>
    </html>
  );
}
