export const BREEDS: Record<string, string[]> = {
  chien: [
    "Affenpinscher",
    "Afghan Hound",
    "Airedale Terrier",
    "Akita Inu",
    "Alaskan Malamute",
    "American Bully",
    "American Cocker Spaniel",
    "American Staffordshire Terrier",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Beauceron",
    "Berger Allemand",
    "Berger Australien",
    "Berger Belge Malinois",
    "Berger Belge Tervueren",
    "Berger Blanc Suisse",
    "Berger de Beauce",
    "Berger de Brie",
    "Berger des Pyrenees",
    "Berger des Shetland",
    "Berger Hollandais",
    "Berger Picard",
    "Bernois (Bouvier Bernois)",
    "Bichon Frise",
    "Bichon Havanais",
    "Bichon Maltais",
    "Bloodhound",
    "Bobtail",
    "Border Collie",
    "Border Terrier",
    "Boston Terrier",
    "Bouledogue Americain",
    "Bouledogue Anglais",
    "Bouledogue Francais",
    "Bouvier Bernois",
    "Bouvier des Flandres",
    "Boxer",
    "Braque Allemand",
    "Braque de Weimar",
    "Braque Hongrois",
    "Briard",
    "Bruno du Jura",
    "Bull Terrier",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corso",
    "Caniche (Toy)",
    "Caniche (Nain)",
    "Caniche (Moyen)",
    "Caniche (Royal)",
    "Carlin (Pug)",
    "Cavalier King Charles",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chow Chow",
    "Clumber Spaniel",
    "Cocker Anglais",
    "Colley (Rough Collie)",
    "Coton de Tulear",
    "Dalmatien",
    "Dandie Dinmont Terrier",
    "Dobermann",
    "Dogue Allemand",
    "Dogue Argentin",
    "Dogue de Bordeaux",
    "Dogue du Tibet",
    "English Springer Spaniel",
    "Epagneul Breton",
    "Epagneul Papillon",
    "Eurasier",
    "Fila Brasileiro",
    "Flat-Coated Retriever",
    "Fox Terrier",
    "Golden Retriever",
    "Gordon Setter",
    "Grand Bouvier Suisse",
    "Grand Danois",
    "Greyhound",
    "Griffon Bruxellois",
    "Husky Siberien",
    "Irish Setter",
    "Irish Wolfhound",
    "Jack Russell Terrier",
    "Kangal",
    "Keeshond",
    "Kerry Blue Terrier",
    "King Charles Spaniel",
    "Komondor",
    "Kuvasz",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Landseer",
    "Leonberg",
    "Levrier Afghan",
    "Levrier Greyhound",
    "Levrier Whippet",
    "Lhassa Apso",
    "Loulou de Pomeranie",
    "Malamute de l'Alaska",
    "Malinois",
    "Mastiff Anglais",
    "Mudi",
    "Newfoundland (Terre-Neuve)",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Pinscher Nain",
    "Pointer Anglais",
    "Podenco",
    "Pomeranian",
    "Rottweiler",
    "Saint-Bernard",
    "Saluki",
    "Samoyede",
    "Schipperke",
    "Schnauzer Geant",
    "Schnauzer Moyen",
    "Schnauzer Nain",
    "Setter Anglais",
    "Setter Irlandais",
    "Shar Pei",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Skye Terrier",
    "Sloughi",
    "Spitz Allemand",
    "Spitz Finlandais",
    "Spitz Japonais",
    "Springer Anglais",
    "Staffie (Staffordshire Bull Terrier)",
    "Teckel (Dachshund)",
    "Terre-Neuve",
    "Terrier Ecossais",
    "Terrier Irlandais",
    "Tervueren",
    "Welsh Corgi Cardigan",
    "Welsh Corgi Pembroke",
    "Welsh Terrier",
    "West Highland White Terrier",
    "Whippet",
    "Yorkshire Terrier",
  ],
  chat: [
    "Abyssin",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Angora Turc",
    "Balinais",
    "Bengal",
    "Birman (Sacre de Birmanie)",
    "Bleu Russe",
    "Bombay",
    "British Longhair",
    "British Shorthair",
    "Burmese",
    "Burmilla",
    "California Spangled",
    "Ceylan",
    "Chartreux",
    "Chausie",
    "Cornish Rex",
    "Cymric",
    "Devon Rex",
    "Donskoy (Don Sphynx)",
    "Egyptian Mau",
    "European Shorthair",
    "Exotic Shorthair",
    "German Rex",
    "Havana Brown",
    "Highland Fold",
    "Himalayen",
    "Japanese Bobtail",
    "Khao Manee",
    "Korat",
    "Kurilian Bobtail",
    "LaPerm",
    "Lykoi",
    "Maine Coon",
    "Manx",
    "Mau Egyptien",
    "Munchkin",
    "Nebelung",
    "Norvegien (des Forets)",
    "Ocicat",
    "Oriental Shorthair",
    "Persan",
    "Peterbald",
    "Pixie-Bob",
    "Ragamuffin",
    "Ragdoll",
    "Russian Blue",
    "Savannah",
    "Scottish Fold",
    "Scottish Straight",
    "Selkirk Rex",
    "Serengeti",
    "Siamois",
    "Siberien",
    "Singapura",
    "Snowshoe",
    "Sokoke",
    "Somali",
    "Sphynx",
    "Thai",
    "Tiffany",
    "Tonkinois",
    "Toyger",
    "Turc de Van",
    "York Chocolat",
  ],
  lapin: [
    "Angora Anglais",
    "Angora Francais",
    "Angora Geant",
    "Argente de Champagne",
    "Belier Anglais",
    "Belier Francais",
    "Belier Hollandais (Holland Lop)",
    "Belier Nain",
    "Blanc de Hotot",
    "Blanc de Nouvelle-Zelande",
    "Blanc de Vendee",
    "Bleu de Vienne",
    "Californien",
    "Castor Rex",
    "Chamois de Thuringe",
    "Chinchilla",
    "Dwarf Hotot",
    "Fauve de Bourgogne",
    "Flemish Giant (Geant des Flandres)",
    "Geant Papillon Francais",
    "Gris du Bourbonnais",
    "Havane",
    "Hermine (Polish)",
    "Hollandais (Dutch)",
    "Jersey Wooly",
    "Lievre Belge",
    "Lionhead (Tete de Lion)",
    "Mini Lop",
    "Mini Rex",
    "Nain Belier",
    "Nain Colore",
    "Nain de Couleur",
    "Netherland Dwarf",
    "Noir de Vienne",
    "Papillon Anglais",
    "Perle Feh",
    "Petit Russe",
    "Rex",
    "Rhinelander",
    "Satin",
    "Silver Fox",
    "Tan",
    "Thuringer",
  ],
  oiseau: [
    "Amazone",
    "Ara Bleu et Jaune",
    "Ara Chloroptere",
    "Ara Hyacinthe",
    "Ara Macao",
    "Cacatoes a Huppe Jaune",
    "Cacatoes Rosalbin",
    "Calopsitte (Cockatiel)",
    "Canari",
    "Cardinal",
    "Colombe Diamant",
    "Conure Soleil",
    "Conure a Joues Vertes",
    "Diamant de Gould",
    "Diamant Mandarin",
    "Eclectus",
    "Gris du Gabon",
    "Inséparable (Agapornis)",
    "Kakariki",
    "Loriquet Arc-en-ciel",
    "Mainate",
    "Merle",
    "Moineau du Japon",
    "Mynah",
    "Padda de Java",
    "Perroquet Jardine",
    "Perroquet Senegalais",
    "Perruche a Collier",
    "Perruche Alexandre",
    "Perruche Bourke",
    "Perruche Calopsitte",
    "Perruche Catherine",
    "Perruche Ondulée",
    "Perruche Splendide",
    "Perruche Turquoisine",
    "Pionus",
    "Quaker (Perruche Moine)",
    "Roseicollis",
    "Toucan",
    "Tourterelle",
    "Youyou du Senegal",
  ],
  rongeur: [
    "Chinchilla",
    "Cochon d'Inde (Cobaye) Abyssinien",
    "Cochon d'Inde (Cobaye) Coronet",
    "Cochon d'Inde (Cobaye) Lisse",
    "Cochon d'Inde (Cobaye) Peruvien",
    "Cochon d'Inde (Cobaye) Rex",
    "Cochon d'Inde (Cobaye) Rosette",
    "Cochon d'Inde (Cobaye) Shelti",
    "Cochon d'Inde (Cobaye) Skinny",
    "Cochon d'Inde (Cobaye) Teddy",
    "Cochon d'Inde (Cobaye) Texel",
    "Degu",
    "Ecureuil de Coree",
    "Ecureuil de Richardson",
    "Furet Albinos",
    "Furet Champagne",
    "Furet Putoise",
    "Furet Zibeline",
    "Gerbille",
    "Hamster Chinois",
    "Hamster Dore (Syrien)",
    "Hamster Nain Campbell",
    "Hamster Nain de Roborovski",
    "Hamster Nain Russe",
    "Lapin Nain (voir categorie lapin)",
    "Octodon",
    "Rat Domestique (Dumbo)",
    "Rat Domestique (Hairless)",
    "Rat Domestique (Husky)",
    "Rat Domestique (Rex)",
    "Rat Domestique (Standard)",
    "Souris Domestique",
    "Tamia (Chipmunk)",
  ],
  autre: [
    "Axolotl",
    "Bernard l'Hermite",
    "Boa Constrictor",
    "Cameleon Panthere",
    "Cameleon Yemen",
    "Chinchilla",
    "Dragon Barbu (Pogona)",
    "Furet",
    "Gecko Leopard",
    "Grenouille Dendrobate",
    "Herisson Pygmee",
    "Iguane Vert",
    "Poisson Betta",
    "Poisson Combattant",
    "Poisson Rouge",
    "Python Royal",
    "Serpent des Bles",
    "Serpent Roi",
    "Sugar Glider",
    "Tortue d'Hermann",
    "Tortue de Floride",
    "Tortue Grecque",
    "Tortue Sulcata",
    "Varan des Savanes",
  ],
};
