export const CANTONS = [
  { code: "AG", name: "Argovie" },
  { code: "AI", name: "Appenzell Rhodes-Interieures" },
  { code: "AR", name: "Appenzell Rhodes-Exterieures" },
  { code: "BE", name: "Berne" },
  { code: "BL", name: "Bale-Campagne" },
  { code: "BS", name: "Bale-Ville" },
  { code: "FR", name: "Fribourg" },
  { code: "GE", name: "Geneve" },
  { code: "GL", name: "Glaris" },
  { code: "GR", name: "Grisons" },
  { code: "JU", name: "Jura" },
  { code: "LU", name: "Lucerne" },
  { code: "NE", name: "Neuchatel" },
  { code: "NW", name: "Nidwald" },
  { code: "OW", name: "Obwald" },
  { code: "SG", name: "Saint-Gall" },
  { code: "SH", name: "Schaffhouse" },
  { code: "SO", name: "Soleure" },
  { code: "SZ", name: "Schwyz" },
  { code: "TG", name: "Thurgovie" },
  { code: "TI", name: "Tessin" },
  { code: "UR", name: "Uri" },
  { code: "VD", name: "Vaud" },
  { code: "VS", name: "Valais" },
  { code: "ZG", name: "Zoug" },
  { code: "ZH", name: "Zurich" },
];
