export const CITIES: Record<string, string[]> = {
  AG: [
    "Aarau", "Baden", "Brugg", "Lenzburg", "Oftringen",
    "Rheinfelden", "Wettingen", "Wohlen", "Zofingen", "Zurzach",
    "Aarburg", "Bremgarten", "Frick", "Kaiseraugst", "Muri",
    "Oberentfelden", "Obersiggenthal", "Spreitenbach", "Suhr", "Turgi",
    "Untersiggenthal", "Windisch",
  ],
  AI: [
    "Appenzell", "Gonten", "Haslen", "Oberegg", "Schwende-Ruete",
  ],
  AR: [
    "Herisau", "Teufen", "Speicher", "Trogen", "Heiden",
    "Urnaesch", "Walzenhausen", "Buhler", "Gais",
  ],
  BE: [
    "Berne", "Bienne", "Thoune", "Burgdorf", "Interlaken",
    "Langenthal", "Koniz", "Moutier", "Spiez", "Steffisburg",
    "Lyss", "Muensingen", "Ostermundigen", "Ittigen", "Worb",
    "Belp", "Herzogenbuchsee", "Kirchberg", "Langnau im Emmental",
    "Muri bei Bern", "Nidau", "Saanen", "Tavannes", "Tramelan",
    "Bolligen", "Bremgarten bei Bern", "Zollikofen", "Muenchenbuchsee",
    "Hilterfingen", "Heimberg", "Uetendorf", "Wichtrach",
  ],
  BL: [
    "Allschwil", "Binningen", "Birsfelden", "Liestal", "Muenchenstein",
    "Muttenz", "Oberwil", "Pratteln", "Reinach", "Sissach",
    "Aesch", "Arlesheim", "Bottmingen", "Gelterkinden", "Laufen",
    "Therwil",
  ],
  BS: [
    "Bale", "Riehen", "Bettingen",
  ],
  FR: [
    "Fribourg", "Bulle", "Morat", "Romont", "Estavayer-le-Lac",
    "Marly", "Villars-sur-Glane", "Givisiez", "Granges-Paccot",
    "Chatel-Saint-Denis", "Duedingen", "Tafers", "Wuennewil-Flamatt",
    "Courtepin", "Belfaux", "Attalens", "Vaulruz",
  ],
  GE: [
    "Geneve", "Carouge", "Lancy", "Meyrin", "Onex",
    "Vernier", "Thonex", "Grand-Saconnex", "Plan-les-Ouates",
    "Chene-Bougeries", "Bernex", "Satigny", "Pregny-Chambesy",
    "Chene-Bourg", "Cologny", "Confignon", "Perly-Certoux",
    "Vandoeuvres", "Veyrier",
  ],
  GL: [
    "Glaris", "Naefels", "Niederurnen", "Ennenda", "Mollis",
    "Linthal", "Elm", "Bilten", "Obstalden",
  ],
  GR: [
    "Coire", "Davos", "Arosa", "Ilanz", "Klosters",
    "Landquart", "Lenzerheide", "Pontresina", "Poschiavo",
    "Saint-Moritz", "Scuol", "Thusis", "Flims", "Laax",
    "Domat/Ems", "Igis", "Maienfeld", "Zizers",
  ],
  JU: [
    "Delemont", "Porrentruy", "Saignelegier", "Courrendlin",
    "Courroux", "Courgenay", "Bassecourt", "Alle", "Fontenais",
    "Les Breuleux", "Develier", "Vicques", "Courtedoux",
    "Les Bois", "Le Noirmont",
  ],
  LU: [
    "Lucerne", "Emmen", "Kriens", "Horw", "Ebikon",
    "Sursee", "Hochdorf", "Meggen", "Rothenburg", "Root",
    "Willisau", "Entlebuch", "Wolhusen", "Adligenswil",
    "Buchrain", "Dagmersellen", "Hildisrieden", "Malters",
    "Neuenkirch", "Sempach", "Weggis",
  ],
  NE: [
    "Neuchatel", "La Chaux-de-Fonds", "Le Locle", "Boudry",
    "Cortaillod", "Fleurier", "Peseux", "Saint-Blaise",
    "Val-de-Travers", "Hauterive", "Marin-Epagnier",
    "Colombier", "Corcelles-Cormondrèche", "Bevaix",
  ],
  NW: [
    "Stans", "Hergiswil", "Buochs", "Ennetbuergen",
    "Beckenried", "Wolfenschiessen", "Dallenwil",
  ],
  OW: [
    "Sarnen", "Kerns", "Alpnach", "Engelberg", "Giswil",
    "Lungern", "Sachseln",
  ],
  SG: [
    "Saint-Gall", "Rapperswil-Jona", "Wil", "Gossau",
    "Rorschach", "Buchs", "Alstaetten", "Flawil",
    "Uzwil", "Wattwil", "Uznach", "Bad Ragaz",
    "Goldach", "Wittenbach", "Steinach", "Sargans",
    "Walenstadt", "Kirchberg", "Oberuzwil",
  ],
  SH: [
    "Schaffhouse", "Neuhausen am Rheinfall", "Thayngen",
    "Beringen", "Hallau", "Stein am Rhein", "Schleitheim",
  ],
  SO: [
    "Soleure", "Olten", "Grenchen", "Zuchwil", "Derendingen",
    "Bettlach", "Trimbach", "Balsthal", "Dornach", "Breitenbach",
    "Oensingen", "Schoenenwerdr", "Haegendirf",
  ],
  SZ: [
    "Schwyz", "Einsiedeln", "Freienbach", "Kuesnacht",
    "Lachen", "Wollerau", "Arth", "Brunnen", "Goldau",
    "Ingenbohl", "Altendorf", "Galgenen",
  ],
  TG: [
    "Frauenfeld", "Kreuzlingen", "Romanshorn", "Amriswil",
    "Arbon", "Weinfelden", "Bischofszell", "Diessenhofen",
    "Muellheim", "Sirnach", "Steckborn", "Aadorf",
  ],
  TI: [
    "Bellinzone", "Lugano", "Locarno", "Mendrisio", "Chiasso",
    "Ascona", "Biasca", "Giubiasco", "Minusio", "Massagno",
    "Paradiso", "Viganello", "Agno", "Airolo", "Coldrerio",
    "Losone", "Muralto", "Stabio", "Tenero-Contra",
  ],
  UR: [
    "Altdorf", "Andermatt", "Erstfeld", "Flueelen",
    "Schattdorf", "Silenen", "Buerglen", "Seedorf",
  ],
  VD: [
    "Lausanne", "Montreux", "Vevey", "Nyon", "Morges",
    "Renens", "Yverdon-les-Bains", "Pully", "Prilly", "Ecublens",
    "Gland", "Aigle", "Bex", "Payerne", "Moudon",
    "Orbe", "Rolle", "Crissier", "Bussigny", "Lutry",
    "La Tour-de-Peilz", "Chavannes-pres-Renens", "Epalinges",
    "Le Mont-sur-Lausanne", "Saint-Sulpice", "Villeneuve",
    "Aubonne", "Chavornay", "Cossonay", "Echallens",
    "Leysin", "Penthalaz", "Romainmotier", "Sainte-Croix",
    "Vallorbe", "Grandson", "Avenches", "Cully",
  ],
  VS: [
    "Sion", "Sierre", "Martigny", "Monthey", "Brig-Glis",
    "Visp", "Naters", "Saas-Fee", "Verbier", "Zermatt",
    "Crans-Montana", "Fully", "Conthey", "Saxon", "Saint-Maurice",
    "Collombey-Muraz", "Leukerbad", "Bagnes", "Salvan",
    "Savièse", "Ardon", "Vetroz", "Chalais", "Grimisuat",
  ],
  ZG: [
    "Zoug", "Baar", "Cham", "Huenenberg", "Risch-Rotkreuz",
    "Steinhausen", "Menzingen", "Unteraegeri", "Oberaegeri",
    "Walchwil", "Neuheim",
  ],
  ZH: [
    "Zurich", "Winterthour", "Uster", "Duebendorf", "Dietikon",
    "Wetzikon", "Buelach", "Horgen", "Kloten", "Opfikon",
    "Thalwil", "Illnau-Effretikon", "Wallisellen", "Adliswil",
    "Regensdorf", "Volketswil", "Kuesnacht", "Meilen",
    "Rueti", "Waedenswil", "Affoltern am Albis", "Bassersdorf",
    "Birmensdorf", "Embrach", "Faellanden", "Greifensee",
    "Langnau am Albis", "Maennedorf", "Oberrieden", "Pfaeffikon",
    "Richterswil", "Schlieren", "Staefa", "Uitikon",
    "Urdorf", "Zollikon", "Zumikon",
  ],
};
