export const TRAITS: Record<string, string[]> = {
  chien: [
    "Joueur",
    "Calme",
    "Energique",
    "Calin",
    "Protecteur",
    "Obeissant",
    "Independant",
    "Sociable avec les chiens",
    "Sociable avec les chats",
    "Bon avec les enfants",
    "Craintif",
    "Dominant",
    "Fugueur",
    "Aboyeur",
    "Destructeur quand seul",
    "Aime l'eau",
    "Sportif",
    "Gourmand",
    "Pot de colle",
    "Bon gardien",
  ],
  chat: [
    "Joueur",
    "Calme",
    "Calin",
    "Independant",
    "Curieux",
    "Chasseur",
    "Bavard",
    "Discret",
    "Sociable avec les chats",
    "Sociable avec les chiens",
    "Bon avec les enfants",
    "Craintif",
    "Chat d'interieur",
    "Chat d'exterieur",
    "Grimpeur",
    "Dormeur",
    "Gourmand",
    "Pot de colle",
    "Territorial",
    "Nocturne",
  ],
  lapin: [
    "Joueur",
    "Calme",
    "Calin",
    "Curieux",
    "Craintif",
    "Sociable avec les lapins",
    "Independant",
    "Bon avec les enfants",
    "Actif",
    "Mordilleur",
    "Propre",
    "Gourmand",
    "Aime creuser",
    "Aime les caresses",
  ],
  oiseau: [
    "Chanteur",
    "Bavard",
    "Calme",
    "Joueur",
    "Calin",
    "Curieux",
    "Craintif",
    "Sociable avec les oiseaux",
    "Bon avec les enfants",
    "Independant",
    "Imitateur",
    "Bruyant",
    "Doux",
    "Mordilleur",
    "Acrobate",
  ],
  rongeur: [
    "Joueur",
    "Calme",
    "Curieux",
    "Craintif",
    "Sociable",
    "Nocturne",
    "Actif",
    "Mordilleur",
    "Doux",
    "Bon avec les enfants",
    "Grimpeur",
    "Aime creuser",
    "Propre",
    "Gourmand",
  ],
  autre: [
    "Calme",
    "Curieux",
    "Craintif",
    "Sociable",
    "Independant",
    "Actif",
    "Nocturne",
    "Doux",
    "Bon avec les enfants",
    "Territorial",
    "Joueur",
    "Gourmand",
  ],
};
